### ISSUE TITLE
An Error Occurred (Teleporting Between Dimensions)

### ISSUE THREAD

**Issue by blockswerker** [nothub/SafeTP#12]
The latest release adds a much needed feature to the SafeTP plugin (max. distance between players) but if a tpa request is sent to a player in a different dimension it generates a generic "an error occured" message. Could inter-dimensional tpa be enabled or could the messaging be updated to tell players that they need to be in the same dimension?

**Comment by nothub** [comment]
Hi, thanks for your ticket.
I am unable to reproduce the described problem, could you add more information or a logfile?
There is no restriction to teleport between dimensions in any way.

**Comment by blockswerker** [comment]
This is the log file, thanks for taking a look. I think it has to do with calculating distance between worlds. I tested it overworld to nether, nether to end, and visa versa.

11.02 11:26:21 [Server] INFO RustJunky issued server command: /tpa blockswerker
11.02 11:26:21 [Server] ERROR null
11.02 11:26:21 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'tpa' in plugin SafeTP v2.3.1
11.02 11:26:21 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1869) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1677) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1060) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
11.02 11:26:21 [Server] INFO Caused by: java.lang.IllegalArgumentException: Cannot measure distance between world and world_nether
11.02 11:26:21 [Server] INFO at org.bukkit.Location.distanceSquared(Location.java:510) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO at org.bukkit.Location.distance(Location.java:493) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO at not.hub.safetp.SafeTP.isTooFar(SafeTP.java:279) ~[?:?]
11.02 11:26:21 [Server] INFO at not.hub.safetp.SafeTP.askTP(SafeTP.java:118) ~[?:?]
11.02 11:26:21 [Server] INFO at not.hub.safetp.SafeTP.onCommand(SafeTP.java:76) ~[?:?]
11.02 11:26:21 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-387]
11.02 11:26:21 [Server] INFO ... 17 more

**Comment by nothub** [comment]
hm okay so i just tesed with paper-1.12.2-1618.jar and paper-1.15.2-391.jar and i cant reproduce the problem, every comibnation of worlds to teleport to/from works. are you using any other plugins? you can send me a message on discord if you want to exchange infos faster: hub#6408

//edit:
nvm, i think i found the problem, it was introduced with the last feature.

**Comment by nothub** [comment]
made a fix, gonna test again and release a new jar.

**Comment by nothub** [comment]
fix with release of 2.3.2 at commit f666afca25fd2693dbca65f7cc126ce12bfe317e
