### ISSUE TITLE
add a cooldown

### ISSUE THREAD

**Issue by bierdosenhalter** [nothub/SafeTP#3]
cause "1______  [said]
tpa should have a 15 min cooldown or something
2019/12/13 16:15:20"

enable toggle and timespan configurable via config

**Comment by bierdosenhalter** [comment]
also
![grafik](https://user-images.githubusercontent.com/529651/71088826-b6495f80-219f-11ea-9ba0-a7cc216e3298.png)

**Comment by nothub** [comment]
![](https://i.imgur.com/scnk0m3.png)
